# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ryu's Shikigami
# logoImagePath: https://w7.pngwing.com/pngs/985/67/png-transparent-blue-logo-circle-logo-symbol-font-templates-blue-angle-text-thumbnail.png
email: mateus.ryu8@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "shikigami.ryu.dev.br" # the base hostname & protocol for your site, e.g. http://example.com
language: "pt-BR"

analytics: true
google_tag: "G-84RVTTFH0L"

collections:
  doc:
    output: true
    sort_by: chapter
    permalink: /:collection/:name

defaults:
  - scope:
      path: "api/datas"
    values:
      layout: "no_content"

  - scope:
      path: ""
      type: "doc"
    values:
      layout: "doc"

  - scope:
      path: "api/ideias"
    values:
      layout: "no_content"

  - scope:
      path: "api/mapas"
    values:
      layout: "map"

  - scope:
      path: "api/rascunhos"
    values:
      layout: "no_content"